### PR TITLE
More Python 3 compatibility; version 1.0.6

### PR DESCRIPTION
**Pull request by mpetazzoni**
Updated Protobuf generated Python source code, generated with version 3
of the Protocol Buffer compiler which now produces Python 3 compatible
source code. We now therefore require protobuf >= 3.0.0.

### CODE REVIEW

**Comment by tedoc2000** [comment]
I assume you sent datapoint and say them arrive?

**Comment by jtprobst** [comment]
I can confirm that the problem from #31 appears to be gone:
```
pip install git+https://github.com/signalfx/signalfx-python@wip/protobuf-v3
```

```
root@4781233a211a:/# python
Python 3.5.2 (default, Sep 24 2016, 05:23:05) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import signalfx
>>> signalfx.SignalFx().ingest("asdf")
<signalfx.ingest.ProtoBufSignalFxIngestClient object at 0x7fa297789a58>
>>> 
```

**Comment by tedoc2000** [comment]
nm. I tested it myself and it works fine. Merging

**Comment by mpetazzoni** [comment]
Sorry for lack of response, I was away without connectivity. I did test this one indeed. I'll do the 1.0.6 release if it hasn't been done already. Thanks for merging!

**Pull request merged**
